name: Python Tests

on:
  pull_request:
    branches: [main]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build docker image
      working-directory: ./
      run: docker build -f docker/test-server/Dockerfile -t test-server backend/server/
    - name: Run tests
      working-directory: ./
      run: docker run --rm test-server