name: Python Tests

on:
  pull_request:
    branches: [main]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: Build docker image
      run: docker build -f docker/test-server/Dockerfile -t test-server ./backend/server/
    - name: Run tests
      run: docker run --rm test-server